// SPDX-FileCopyrightText: 2026 Jowi Aoun
// SPDX-License-Identifier: MPL-2.0
//
// Local time, from a series of UTC instants and a zone. Twice a year this is
// the difference between a correct chart and a plausible one.
//
// ============================================================================
// WHY THIS FILE EXISTS AT ALL
//
// Because Open-Meteo's `timezone=auto` does not do what its name suggests, and
// the way it fails is invisible for ten and a half months of the year.
//
// Ask for a forecast with `timezone=auto` and the response carries three
// things: an hourly `time` array of *naive* local timestamps ("2026-07-30T00:00",
// no zone, no offset), a `timezone` of "America/Toronto", and a single
// `utc_offset_seconds` of -14400. The naive timestamps are simply the UTC
// series with that one offset added to every element. There is no second
// offset and there is no transition:
//
//     $ …/v1/archive?…&timezone=auto&start_date=2026-01-10&end_date=2026-01-12
//     {"utc_offset_seconds":-14400, "timezone_abbreviation":"GMT-4",
//      "daily":{"sunrise":["2026-01-10T08:50", …]}}
//
// That is January in Toronto, which is UTC-5, and the sun rose at 07:50. Every
// timestamp in that response — every hour of the chart, both ends of the day,
// sunrise, sunset, moonrise — is an hour late, and nothing in the payload says
// so. Verified live against the service, 2026-07-31, and cross-checked against
// the same request with `timezone=UTC`: the two series are identical values
// under labels that differ by a constant.
//
// For a forecast issued today that matters not at all, because today's offset
// is today's offset. It matters on the sixteenth of October, when the 16-day
// window reaches past the first Sunday in November and every hour after the
// transition is labelled with the wrong clock — and it matters on the day the
// user opens the app *during* that window, which is a day nobody will be
// looking at this code.
//
// ============================================================================
// THE FIX, AND WHAT IT BUYS
//
// The adapter throws the labels away and keeps the instants:
//
//     utc = naive_local - utc_offset_seconds
//
// which is exact, because the labels were generated by adding that same
// constant. Everything libclima stores is then a true UTC instant — the
// invariant libclima/core/clock.h already sets for the rest of the engine —
// and the *real* zone comes from the response's IANA `timezone` field, applied
// here, by Qt's own zone database.
//
// The consequence is the thing the charts actually need, and it is worth
// stating plainly because it is the opposite of what the input looked like:
//
//     Open-Meteo's local day is always 24 rows. A real local day is not.
//
// Re-expressed in America/Toronto, a uniformly spaced UTC series gives
// 2025-11-02 twenty-five slots (01:00 happens twice) and 2026-03-08 twenty-three
// (02:00 never happens). tests/tst_timeaxis.cpp asserts exactly that against
// two recorded responses, and `indicesOnLocalDate` below is what produces it.
//
// So an hourly axis must be built by walking `hourly.time` and asking this
// file what local hour each element is. It must never be built as
// `startHour + i`: that arithmetic is correct only for a fixed-offset day, and
// app/qml/Clima/mockdata.js's `hourLabel()` does precisely that because a
// hand-written mock has no transitions in it.
//
// ---- when Qt does not know the zone ------------------------------------------
//
// A zone id Qt cannot resolve — an old tzdata, a musl build without one, a
// provider inventing a name — falls back to a fixed offset built from
// `utc_offset_seconds`. That is Open-Meteo's own behaviour, so the fallback is
// no worse than not having tried, and it is a valid QTimeZone so nothing
// downstream has to test for it.

#pragma once

#include <QDate>
#include <QDateTime>
#include <QList>
#include <QString>
#include <QTimeZone>

namespace clima {

// The zone named by `ianaId`, or a fixed-offset zone of `fallbackOffsetSeconds`
// when Qt has never heard of it. Always returns a valid QTimeZone.
QTimeZone zoneFor(const QString &ianaId, int fallbackOffsetSeconds);

// The instant a naive local timestamp denotes, given the constant offset the
// timestamp was generated with. `naiveLocal` is "2026-07-30T00:00" or
// "2026-07-30" — Open-Meteo writes both, and a bare date means local midnight.
//
// Returns an invalid QDateTime for empty or unparseable input, which is how a
// null sunrise or a moon that does not rise today arrives.
QDateTime utcFromNaiveLocal(const QString &naiveLocal, int offsetSeconds);

// Which elements of a UTC series fall on `date` in `zone`.
//
// Contiguous by construction for a sorted input, so callers wanting a span can
// take first() and last(). Twenty-five entries on a fall-back day and
// twenty-three on a spring-forward one — see the header.
QList<int> indicesOnLocalDate(const QList<QDateTime> &utc, const QTimeZone &zone, QDate date);

// The local calendar date an instant falls on.
QDate localDateOf(const QDateTime &utc, const QTimeZone &zone);

// Where an instant sits on a local clock face, in the minutes-past-midnight
// app/qml/Clima/detaildata.js places sun and moon on an arc with — counted
// from midnight at the start of `reference`.
//
// `reference` rather than the event's own date, and that is the whole point of
// the signature. Above the Arctic circle in July, Open-Meteo reports sunrise as
// the day's own midnight and sunset as the *next* day's midnight; asked for
// minutes past its own midnight, that sunset answers 0 and the Sun card draws
// an arc of zero length on the one day of the year the sun never sets. Counted
// from the reference date it answers 1440, and the arc is full, which is what
// a day of midnight sun looks like.
//
// Consequently the result is not clamped to [0, 1440): an event before the
// reference midnight is negative and one after the following midnight is over
// 1440. Both are real answers — a moon that rose last night is genuinely at
// -35 minutes — and clamping them would put it at dawn.
//
// It is the clock reading and not the elapsed time, which matters on exactly
// the two days a year this file is about: see the implementation, where the
// difference is 475 against 415 for a sunrise everything else on the page
// calls 6:55.
//
// Returns std::numeric_limits<int>::min() for an invalid instant, so an absent
// event cannot be mistaken for one at midnight. Use `hasMinuteOfDay()`.
int  minutesFromLocalMidnight(const QDateTime &utc, const QTimeZone &zone, QDate reference);
bool hasMinuteOfDay(int minutes);

} // namespace clima
